version: "3.8"

services:
  authenticationapi:
    build:
      context: .
      dockerfile: Services/Authentication/AuthenticationAPI/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__DefaultConnection=${AUTH_CONNECTION}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - RabbitMq__Host=${RABBITMQ_HOST}
      - RabbitMq__Username=${RABBITMQ_USERNAME}
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - voucher-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${AUTH_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - voucher-network
  
  postgres:
    image: postgres:16
    container_name: voucher_postgres
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voucher-network

  vouchergrpc:
    image: ${DOCKER_REGISTRY-}vouchergrpc
    build:
      context: .
      dockerfile: Services/Voucher/VoucherGrpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__DefaultConnection=${PG_CONNECTION}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - RabbitMq__Host=${RABBITMQ_HOST}
      - RabbitMq__Username=${RABBITMQ_USERNAME}
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5001:80"
    networks:
      - voucher-network

  sagaservice:
    image: ${DOCKER_REGISTRY-}sagaservice
    build:
      context: .
      dockerfile: Services/SagaService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RabbitMq__Host=${RABBITMQ_HOST}
      - RabbitMq__Username=${RABBITMQ_USERNAME}
      - RabbitMq__Password=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    networks:
      - voucher-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - voucher-network


volumes:
  sqlserver_data:
  postgres_data:

networks:
  voucher-network:
    driver: bridge

