version: "3.8"

services:
  authenticationapi:
    build:
      context: .
      dockerfile: Services/Authentication/AuthenticationAPI/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDb;User=sa;Password=Your_password123;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - voucher-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - voucher-network

volumes:
  sqlserver_data:

networks:
  voucher-network:
    driver: bridge
